## Start modelering van voorspellingsmodel

### Import data

In [433]:
import pandas as pd
import category_encoders as ce
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

df = pd.read_csv("../../csv/new_train_data/train_CarBreakDown.csv")

# Split method

# df_safe = df[df['breakdown_next_30_days'] == 0]
# df_breakdown = df[df['breakdown_next_30_days'] == 1]

### Splits data in x en y en in train en test data

In [434]:
used_features =['vehicle_brand','vehicle_age_years','mileage_km','engine_hours','last_service_km_ago','oil_quality_pct','avg_trip_length_km','weather_exposure','fuel_type','cleanliness_score','driver_satisfaction_score','tyre_type']

x = df[used_features]
y = df[['breakdown_next_30_days']]

# Split method

# x_safe = df_safe[used_features]
# x_breakdown = df_breakdown[used_features]
# y_safe = df_safe[['breakdown_next_30_days']]
# y_breakdown = df_breakdown[['breakdown_next_30_days']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [435]:
x

,vehicle_brand,vehicle_age_years,mileage_km,engine_hours,last_service_km_ago,oil_quality_pct,avg_trip_length_km,weather_exposure,fuel_type,cleanliness_score,driver_satisfaction_score,tyre_type
0,Toyota,5.0,92828.113285,2986.923461,1845.744691,54.060416,6.464345,high,diesel,72.246829,4.719607,winter
1,Renault,1.0,209439.442769,7156.897259,3527.010815,52.147399,1.458703,high,hybrid,57.117174,7.676373,summer
2,Ford,2.0,113057.424374,3818.890986,2585.704820,48.387331,21.020533,low,diesel,86.677049,6.622987,summer
3,Ford,14.0,72863.780220,2737.020177,1940.911273,29.165972,38.882832,other,petrol,72.965514,6.923436,all-season
4,Volkswagen,8.0,92034.533322,2890.748001,4632.801091,61.055831,86.167646,low,diesel,60.972122,7.588807,winter
...,...,...,...,...,...,...,...,...,...,...,...,...
709,Toyota,7.0,84639.766973,3133.654549,801.508052,53.181356,12.044847,low,petrol,74.254700,7.883355,summer
710,Ford,6.0,73047.389818,2678.999483,14085.805874,72.835609,43.227761,high,diesel,73.314438,9.001056,summer
711,Toyota,9.0,127224.810750,4106.036923,23433.319506,69.923976,1.773332,medium,petrol,62.945838,5.346505,summer
712,Ford,19.0,74204.367905,2323.811128,6490.998514,60.566073,39.444093,low,diesel,88.354147,5.944547,winter
713,BMW,10.0,198492.993706,6643.176908,3564.136473,82.555275,9.060255,low,diesel,64.073009,6.061162,all-season

In [436]:
y

     breakdown_next_30_days
0                         0
1                         0
2                         0
3                         1
4                         0
..                      ...
709                       0
710                       0
711                       1
712                       0
713                       0

[714 rows x 1 columns]

### Encoding van categorische velden

In [437]:
# !pip install --upgrade category_encoders

category_encoder = ce.OrdinalEncoder(cols = ['vehicle_brand','weather_exposure','fuel_type','tyre_type'])

x_encoded = category_encoder.fit_transform(x_train)

# Split method

# x_safe_encoded = category_encoder.fit_transform(x_safe)
# x_breakdown_encoded = category_encoder.transform(x_breakdown)
x_test_encoded = category_encoder.transform(x_test)
x_encoded

,vehicle_brand,vehicle_age_years,mileage_km,engine_hours,last_service_km_ago,oil_quality_pct,avg_trip_length_km,weather_exposure,fuel_type,cleanliness_score,driver_satisfaction_score,tyre_type
695,1,12.0,65495.106598,2138.954564,735.326533,57.397500,4.694457,1,1,56.860436,6.923436,1
468,2,10.0,114474.085906,3679.847619,9005.406937,48.289531,99.938603,1,2,62.836710,8.607369,1
8,3,3.0,84978.516977,2982.981461,3057.816183,25.032238,60.211130,2,2,91.351108,8.058919,1
5,4,7.0,96693.578035,3031.698781,12182.202261,42.486713,146.055548,1,1,93.122984,6.603669,2
173,5,6.0,112956.224209,3704.610140,29320.299638,30.296275,10.530738,1,3,86.135564,7.762642,3
...,...,...,...,...,...,...,...,...,...,...,...,...
654,1,11.0,147769.547852,4390.683598,2022.529308,68.341879,8.725884,3,3,61.473980,7.009763,1
197,8,9.0,129748.512326,4293.622808,1548.022123,47.165606,8.988239,3,3,88.924257,8.018851,3
137,5,4.0,126208.658952,4285.884719,8608.957847,55.617496,7.478376,1,2,53.532339,7.787112,2
713,2,10.0,198492.993706,6643.176908,3564.136473,82.555275,9.060255,1,1,64.073009,6.061162,1
135,5,2.0,60960.585050,2153.876017,5263.197674,52.428896,4.608913,1,4,41.224535,9.125160,1

### Train model via Random forest

In [438]:
from sklearn.ensemble import RandomForestClassifier
from random import randint

# Split method

# end_df = pd.DataFrame([])
# end_df = pd.concat([end_df, x_breakdown_encoded])
# end_df = pd.concat([end_df, x_safe_encoded.sample(n=x_breakdown_encoded.shape[0])])

clf = RandomForestClassifier(criterion='entropy',n_estimators=100, max_samples = 50, class_weight={0:1, 1:50})
clf = clf.fit(x_encoded, y_train.values.ravel()) # values.ravel() because a warning appears about using a 1d array so we need to flatten it.

# Split method

# use end_df and .sample(n=x_breakdown_encoded.shape[0]*2) instead for the fit

#### Voorspelling output

In [439]:
clf_prediction = clf.predict(x_test_encoded)
print(clf_prediction)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

#### Accuracy weergave

In [440]:
print(f"Accuracy: {metrics.accuracy_score(y_test, clf_prediction)}")

Accuracy: 0.7482517482517482

#### Confusion matrix

In [441]:
confusion_matrix(y_test, clf_prediction)

array([[107,   0],
       [ 36,   0]])

## Spliting the break down and safe results

One of the problems in the dataset was that there is a considarably high amount of non breaking cars. To try and solve this we split the data in two data frames (see # split method), one with only working cars and one with all the cars that brokedown. Then when fitting the model we took a sample of 100 from both then dataframes and combined them to form the train data. This had little effect on the end result with the accurasy and false positives not changing.

In addition we also tried to use duplicate rows of the breakdwon dataframe to see if the problem was the lack of data but this also dit not change it.